#!/usr/bin/env ansible-playbook
---

- name: Set up a shell environment
  hosts: all

  pre_tasks:
      - name: Update apt-cache
        apt:
            update_cache: true
            cache_valid_time: 3600
        become: true
        when: ansible_os_family == "Debian"

  roles:
  - cli

