#!/usr/bin/env ansible-playbook
---

- name: Setup local environment for personal machine
  hosts: localhost
  connection: local

  pre_tasks:
      - name: Update apt-cache
        apt:
            update_cache: true
            cache_valid_time: 3600
        become: true
        when: ansible_os_family == "Debian"

      - name: Update pacman cache
        pacman:
          update_cache: true
        become: true
        when: ansible_os_family == "Archlinux"

      - name: Inastall aur ansible module
        community.general.ansible_galaxy_install:
          type: collection
          name: kewlfft.aur
        when: ansible_os_family == "Archlinux"

  roles:
  - cli

  tasks:
  - include_role:
      name: '{{ item }}'
    with_first_found:
      - files: 
        - '{{ ansible_os_family }}'
        paths:
        - 'roles'
        skip: true
