---

- name: Setup personal shell environment
  hosts: all

  pre_tasks:
      - name: Update apt-cache
        apt:
            update_cache: true
            cache_valid_time: 3600
        become: true
        when: ansible_os_family == Ubuntu

      - name: Update pacman cache
        pacman:
          update_cache: true

  roles:
  - cli

  tasks:
  - include_role:
      name: '{{ item }}'
    with_first_found:
    - '{{ ansible_os_family }}'
