---
# tasks file for Archlinux

- name: Install yay package manager
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present

- name: Install GUI packages
  pacman:
    pkg: '{{ item }}'
    state: present
  become: true
  with_items:
  - xorg
  - xorg-xinit
  - alacritty
  - awesome
  - picom
  - gnu-free-fonts
  - archlinux-wallpaper
  - nautilus
  - lightdm
  - librsvg
  - firefox
  - code

- name: Enable session manager
  systemd:
    name: lightdm
    enabled: true
  become: true