---
# tasks file for Archlinux

- name: Install yay package manager
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present

- name: Install GUI packages
  pacman:
    pkg: '{{ item }}'
    state: present
  become: true
  with_items:
  - xorg
  - xorg-xinit
  - alacritty
  - awesome
  - picom
  - gnu-free-fonts
  - archlinux-wallpaper
  - nautilus
  - lightdm
  - lightdm-webkit2-greeter
  - librsvg
  - firefox

- name: Install AUR packages
  kewlfft.aur.aur:
    name: "{{ item }}"
    use: yay
    state: present
  with_items:
   - vscodium-bin
- name: Enable session manager
  systemd:
    name: lightdm
    enabled: true
  become: true

- name: Configure lightdm greeter
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    search_string: greeter-session
    line: greeter-session=lightdm-webkit2-greeter
  become: true