---
# tasks file for refind
#
- name: Install required packages
  package:
    pkg: "{{ item }}"
    state: present
  become: true
  loop: "{{ refind_packages }}"

- name: Run refind installer
  command:
    cmd: refind-install
    creates: /boot/refind_linux.conf
  become: true

- name: Copy refind theme files
  copy:
    src: "{{ item.src }}"
    dest: "{{ efi_mount }}/EFI/refind/{{ item.dest }}"
  loop:
    - src: refind-theme.conf
      dest: refind-theme.conf
    - src: refind-theme/fonts/
      dest: themes/refind-theme-regular/fonts/
    - src: refind-theme/icons/
      dest: themes/refind-theme-regular/icons/
  become: true

- name: Configure refind
  lineinfile:
    path: "{{ efi_mount }}/EFI/refind/refind.conf"
    search_string: "{{ item.param }}"
    line: "{{ item.param }} {{ item.value }}"
  become: true
  loop:
    - param: timeout
      value: "5"
    - param: scanfor
      value: manual,external,optical
    - param: include
      value: refind-theme.conf
  when: manual_stanzas
