icons_format = "{icon}"
double_click_delay = 200

[theme]
theme = "semi-native"

[icons]
icons = "material-nf"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "net"
format = " $icon {$ssid|$device} "
format_alt = " ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
[[block.click]]
button = "double_left"
cmd = "nm-connection-editor"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "cpu"
format_alt = " $icon $barchart "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
merge_with_next = true

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
merge_with_next = true
[[block.click]]
button = "left"
action = "toggle_mute"
[[block.click]]
button = "double_left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
invert_icons = true

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
