#!/usr/bin/env bash
#
# Based on tmux-sessionizer by ThePrimeagen
#
search_path=${SESSIONIZER_SEARCH:=~/ ~/projects ~/.dotfiles}

if [[ $# -eq 1 ]]; then
    selected=$1
elif command -v fzf &> /dev/null; then
    selected=$(find $search_path -mindepth 1 -maxdepth 2 -type d | fzf)
else
    echo '`fzf` not found and no directory was specified'
	exit 1
fi

if [[ -z $selected ]]; then
    exit 0
fi

# Get only the base directory name
selected_name=$(basename "$selected" | tr . _)

tmux_pid=$(pgrep tmux)

# If we are not in tmux already
if [[ -z $TMUX ]] && [[ -z $tmux_pid ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

# If we are in tmux, but the session doesn't already exist
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
