#!/usr/bin/env bash
#
# Based on tmux-sessionizer by ThePrimeagen
#
__wezterm_set_user_var() {
  if hash base64 2>/dev/null ; then
    if [[ -z "${TMUX}" ]] ; then
      printf "\033]1337;SetUserVar=%s=%s\007" "$1" `echo -n "$2" | base64`
    else
      # <https://github.com/tmux/tmux/wiki/FAQ#what-is-the-passthrough-escape-sequence-and-how-do-i-use-it>
      # Note that you ALSO need to add "set -g allow-passthrough on" to your tmux.conf
      printf "\033Ptmux;\033\033]1337;SetUserVar=%s=%s\007\033\\" "$1" `echo -n "$2" | base64`
    fi
  fi
}

if [[ "$TERM_PROGRAM" != WezTerm ]]; then
    echo 'This script is only compatible with the wezterm multiplexer'
    exit 1
fi

search_path=${SESSIONIZER_SEARCH:=$HOME $HOME/projects $HOME/.dotfiles}

if [[ $# -eq 1 ]]; then
    if command -v realpath; then
        selected=$(realpath "$1")
    else
        selected="$1"
    fi
elif command -v fzf &> /dev/null; then
    selected=$(find $search_path -maxdepth 2 -type d | sort | uniq | fzf)
else
    echo '`fzf` not found and no directory was specified'
    exit 1
fi

if [[ -z $selected ]]; then
    exit 0
fi

__wezterm_set_user_var SESSIONIZER_DIR "$selected"

sleep 1
