pacman_packages:
  - alacritty
  - archlinux-wallpaper
  - archlinux-wallpaper
  - awesome
  - base
  - bitwarden-cli
  - btrfs-progs
  - discord
  - docker
  - docker-compose
  - feh
  - firefox
  - git
  - gnu-free-fonts
  - go
  - gvim
  - gzip
  - librsvg
  - lightdm
  - lightdm-webkit2-greeter
  - neofetch
  - network-manager-applet
  - networkmanager
  - networkmanager-openvpn
  - nitrogen
  - nm-connection-editor
  - obsidian
  - partitionmanager
  - pavucontrol
  - picom
  - pulseaudio
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - pulseaudio-equalizer
  - pulsemixer
  - python
  - python-pip
  - qemu-desktop
  - ranger
  - refind
  - rofi
  - rofi
  - screengrab
  - snapper
  - sudo
  - thermald
  - tree
  - ttf-roboto
  - wget
  - xclip
  - xorg
  - xorg-xinit
  - zip
  - zoom
  - zsh

aur_packages:
 - vscodium-bin
 - lightdm-webkit2-theme-reactive
 - nerd-fonts-cascadia-code
 - nerd-fonts-droid-sans-mono
 - nerd-fonts-inconsolata-go
