#!/usr/bin/env bash

show_opts() {
    echo -en "\0prompt\x1fScreenshot\0no-custom\x1ftrue\n"
    echo -en "region\0display\x1fSelect a region to screenshot\n"
    echo -en "monitor\0display\x1fScreenshot the current monitor\0icon\x1fdisplay\n"
    echo -en "window\0display\x1fScreenshot the current window\n"
}

case "$1" in
    monitor)
        coproc ( sleep 1 && grim -o $(swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name') - | wl-copy && notify-send "Screenshot saved to clipboard" )
        exit 0
        ;;
    window)
        coproc ( sleep 1 && grim -g "$(swaymsg -t get_tree | jq -j '.. | select(.type?) | select(.focused).rect | "\(.x),\(.y) \(.width)x\(.height)"')" - | wl-copy && notify-send "Screenshot saved to clipboard" )
        exit 0
        ;;
    region)
        coproc ( sleep 1 && grim -g "$(slurp)" - | wl-copy && notify-send "Screenshot saved to clipboard" )
        exit 0
        ;;
    *)
        show_opts
esac
