---
# tasks file for cli

- name: Download packages
  package:
      name: "{{ item }}"
      state: present
  with_items:
      - vim
      - zsh
      - git
      - curl
      - wget
      - neofetch
  become: true
  ignore_errors: true

- name: Check for Oh My Zsh
  stat:
      path: /home/{{ user }}/.oh-my-zsh/oh-my-zsh.sh
  register: omz

- name: Install Oh My Zsh
  block:
      - name: Download omz install script
        get_url:
            url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
            dest: /tmp/omz.sh
            mode: "777"

      - name: Run omz install script
        shell: /tmp/omz.sh --unattended
        become: true
        become_user: "{{ user }}"
  when: not omz.stat.exists

- name: OMZ Plugins are installed & up to date
  git:
      repo: "https://github.com/zsh-users/{{ item }}.git"
      dest: "/home/{{ user }}/.oh-my-zsh/custom/plugins/{{ item }}"
  with_items:
      - zsh-autosuggestions
      - zsh-syntax-highlighting

- name: Dotfiles repo is present and up to date
  git:
      repo: https://github.com/bpjordan/dotfiles.git
      dest: /home/{{ user }}/.dotfiles
      force: true

- name: Symlink theme
  file:
      src: /home/{{ user }}/.dotfiles/bjordan.zsh-theme
      dest: /home/{{ user }}/.oh-my-zsh/custom/themes/bjordan.zsh-theme
      state: link
      owner: "{{ user }}"
      group: "{{ user }}"

- name: Dotfiles are symlinked in home
  file:
      src: "/home/{{ user }}/.dotfiles/{{ item }}"
      dest: "/home/{{ user }}/{{ item }}"
      state: link
      force: true
      owner: "{{ user }}"
      group: "{{ user }}"
  with_items:
      - .vimrc
      - .vim
      - .bashrc
      - .gitconfig
      - .zshrc
      - .gtkrc-2.0

- name: Config directory exists
  file:
    path: /home/{{ user }}/.config
    state: directory
    force: true
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Config files are symlinked
  file:
    src: /home/{{ user }}/.dotfiles/.config/{{ item }}
    dest: /home/{{ user }}/.config/{{ item }}
    state: link
    force: true
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
  - awesome
  - alacritty
  - backgrounds
  - gtk-3.0
  - neofetch

- name: zsh set as default shell
  user:
      name: "{{ user }}"
      shell: /usr/bin/zsh
  become: true
