---
# tasks file for cli

- name: Download packages
  package:
      name: "{{ item }}"
      state: present
  loop:
      - vim
      - zsh
      - git
      - curl
      - wget
  become: true
  ignore_errors: true

- name: Dotfiles repo is present and up to date
  git:
      repo: https://github.com/bpjordan/dotfiles.git
      dest: /home/{{ user }}/.dotfiles
      force: true

- name: Dotfiles are symlinked in home
  file:
      src: "/home/{{ user }}/.dotfiles/{{ item }}"
      dest: "/home/{{ user }}/{{ item }}"
      state: link
      force: true
      owner: "{{ user }}"
      group: "{{ user }}"
  loop:
      - .vimrc
      - .vim
      - .bashrc
      - .gitconfig
      - .zshrc
      - .gtkrc-2.0

- name: Config directory exists
  file:
    path: /home/{{ user }}/.config
    state: directory
    force: true
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Config files are symlinked
  file:
    src: /home/{{ user }}/.dotfiles/.config/{{ item }}
    dest: /home/{{ user }}/.config/{{ item }}
    state: link
    force: true
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
  - awesome
  - alacritty
  - backgrounds
  - gtk-3.0
  - neofetch
  - nvim
  - tmux

- name: zsh set as default shell
  user:
      name: "{{ user }}"
      shell: /usr/bin/zsh
  become: true
